export const APPS = [
  {
    id: "snake",
    title: "SNAKE",
    icon: "🐍",
    path: "/claudeapps/snake/",
    description: "Klassisches Snake-Spiel mit drei Schwierigkeitsstufen",
    category: "Spiele",
  },
  {
    id: "memory",
    title: "MEMORY",
    icon: "🧠",
    path: "/claudeapps/memory/",
    description: "Finde alle Kartenpaare in möglichst wenigen Zügen",
    category: "Spiele",
  },
  {
    id: "fifteen",
    title: "15er PUZZLE",
    icon: "🔢",
    path: "/claudeapps/fifteen/",
    description: "Schiebepuzzle – sortiere die Zahlen 1–15, mit persistenter Ergebnis-Historie",
    category: "Spiele",
  },
  {
    id: "poker",
    title: "POKER",
    icon: "🃏",
    path: "/claudeapps/poker/",
    description: "Texas Hold'em gegen 3 KI-Gegner – Fold, Call, Raise oder All-In",
    category: "Spiele",
  },
  {
    id: "taskmanager",
    title: "TASKS",
    icon: "📋",
    path: "/claudeapps/taskmanager/",
    description: "Aufgaben verwalten mit Kanban-Board, Benutzerzuweisung und Statusplan",
    category: "Tools",
  },
  {
    id: "apppp",
    title: "APPPP",
    icon: "📋",
    path: "/claudeapps/apppp/",
    description: "Task Management – separate Instanz mit eigener Datenbank",
    category: "Tools",
  },
  {
    id: "processes",
    title: "PROZESSE",
    icon: "📖",
    path: "/claudeapps/processes/",
    description: "Spezifikationen aller Prozesse – Felder, SLA, Features, Kanban-Gruppen",
    category: "Tools",
  },
  {
    id: "sharehandling",
    title: "SHARE HANDLING",
    icon: "📈",
    path: "/claudeapps/sharehandling/",
    description: "Aktienregister verwalten – Aktionäre, Verkäufe, prozentuale Auswertung, unterschriftsreifes PDF",
    category: "Finanzen",
  },
];
